/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSeoRouteImport } from './routes/_app/seo'
import { Route as AppScreenMonitoringRouteImport } from './routes/_app/screen-monitoring'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppRecruitmentRouteImport } from './routes/_app/recruitment'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppOutreachRouteImport } from './routes/_app/outreach'
import { Route as AppLoginPhotosRouteImport } from './routes/_app/login-photos'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppHrRouteImport } from './routes/_app/hr'
import { Route as AppHowToUseRouteImport } from './routes/_app/how-to-use'
import { Route as AppDevRouteImport } from './routes/_app/dev'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBulkEmailRouteImport } from './routes/_app/bulk-email'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppDealsIndexRouteImport } from './routes/_app/deals.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'
import { Route as AppDealsIdRouteImport } from './routes/_app/deals.$id'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoRoute = AppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenMonitoringRoute = AppScreenMonitoringRouteImport.update({
  id: '/screen-monitoring',
  path: '/screen-monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentRoute = AppRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRoute = AppOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginPhotosRoute = AppLoginPhotosRouteImport.update({
  id: '/login-photos',
  path: '/login-photos',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppHowToUseRoute = AppHowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => AppRoute,
} as any)
const AppDevRoute = AppDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBulkEmailRoute = AppBulkEmailRouteImport.update({
  id: '/bulk-email',
  path: '/bulk-email',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppDealsIdRoute = AppDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AppAccountRoute
  '/analytics': typeof AppAnalyticsRoute
  '/attendance': typeof AppAttendanceRoute
  '/bulk-email': typeof AppBulkEmailRoute
  '/chat': typeof AppChatRoute
  '/crm': typeof AppCrmRoute
  '/dev': typeof AppDevRoute
  '/how-to-use': typeof AppHowToUseRoute
  '/hr': typeof AppHrRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/login-photos': typeof AppLoginPhotosRoute
  '/outreach': typeof AppOutreachRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/recruitment': typeof AppRecruitmentRoute
  '/sales': typeof AppSalesRoute
  '/screen-monitoring': typeof AppScreenMonitoringRoute
  '/seo': typeof AppSeoRoute
  '/tasks': typeof AppTasksRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/deals/': typeof AppDealsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AppAccountRoute
  '/analytics': typeof AppAnalyticsRoute
  '/attendance': typeof AppAttendanceRoute
  '/bulk-email': typeof AppBulkEmailRoute
  '/chat': typeof AppChatRoute
  '/crm': typeof AppCrmRoute
  '/dev': typeof AppDevRoute
  '/how-to-use': typeof AppHowToUseRoute
  '/hr': typeof AppHrRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/login-photos': typeof AppLoginPhotosRoute
  '/outreach': typeof AppOutreachRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/recruitment': typeof AppRecruitmentRoute
  '/sales': typeof AppSalesRoute
  '/screen-monitoring': typeof AppScreenMonitoringRoute
  '/seo': typeof AppSeoRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/deals': typeof AppDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/bulk-email': typeof AppBulkEmailRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dev': typeof AppDevRoute
  '/_app/how-to-use': typeof AppHowToUseRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/login-photos': typeof AppLoginPhotosRoute
  '/_app/outreach': typeof AppOutreachRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/recruitment': typeof AppRecruitmentRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/screen-monitoring': typeof AppScreenMonitoringRoute
  '/_app/seo': typeof AppSeoRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/deals/$id': typeof AppDealsIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/deals/': typeof AppDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/account'
    | '/analytics'
    | '/attendance'
    | '/bulk-email'
    | '/chat'
    | '/crm'
    | '/dev'
    | '/how-to-use'
    | '/hr'
    | '/knowledge'
    | '/login-photos'
    | '/outreach'
    | '/projects'
    | '/recruitment'
    | '/sales'
    | '/screen-monitoring'
    | '/seo'
    | '/tasks'
    | '/admin/settings'
    | '/deals/$id'
    | '/projects/$id'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/account'
    | '/analytics'
    | '/attendance'
    | '/bulk-email'
    | '/chat'
    | '/crm'
    | '/dev'
    | '/how-to-use'
    | '/hr'
    | '/knowledge'
    | '/login-photos'
    | '/outreach'
    | '/projects'
    | '/recruitment'
    | '/sales'
    | '/screen-monitoring'
    | '/seo'
    | '/tasks'
    | '/'
    | '/admin/settings'
    | '/deals/$id'
    | '/projects/$id'
    | '/deals'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/_app/account'
    | '/_app/analytics'
    | '/_app/attendance'
    | '/_app/bulk-email'
    | '/_app/chat'
    | '/_app/crm'
    | '/_app/dev'
    | '/_app/how-to-use'
    | '/_app/hr'
    | '/_app/knowledge'
    | '/_app/login-photos'
    | '/_app/outreach'
    | '/_app/projects'
    | '/_app/recruitment'
    | '/_app/sales'
    | '/_app/screen-monitoring'
    | '/_app/seo'
    | '/_app/tasks'
    | '/_app/'
    | '/_app/admin/settings'
    | '/_app/deals/$id'
    | '/_app/projects/$id'
    | '/_app/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seo': {
      id: '/_app/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AppSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screen-monitoring': {
      id: '/_app/screen-monitoring'
      path: '/screen-monitoring'
      fullPath: '/screen-monitoring'
      preLoaderRoute: typeof AppScreenMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment': {
      id: '/_app/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AppRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach': {
      id: '/_app/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AppOutreachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login-photos': {
      id: '/_app/login-photos'
      path: '/login-photos'
      fullPath: '/login-photos'
      preLoaderRoute: typeof AppLoginPhotosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/how-to-use': {
      id: '/_app/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof AppHowToUseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev': {
      id: '/_app/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AppDevRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bulk-email': {
      id: '/_app/bulk-email'
      path: '/bulk-email'
      fullPath: '/bulk-email'
      preLoaderRoute: typeof AppBulkEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/deals/$id': {
      id: '/_app/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AppDealsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBulkEmailRoute: typeof AppBulkEmailRoute
  AppChatRoute: typeof AppChatRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDevRoute: typeof AppDevRoute
  AppHowToUseRoute: typeof AppHowToUseRoute
  AppHrRoute: typeof AppHrRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLoginPhotosRoute: typeof AppLoginPhotosRoute
  AppOutreachRoute: typeof AppOutreachRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppRecruitmentRoute: typeof AppRecruitmentRoute
  AppSalesRoute: typeof AppSalesRoute
  AppScreenMonitoringRoute: typeof AppScreenMonitoringRoute
  AppSeoRoute: typeof AppSeoRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppDealsIdRoute: typeof AppDealsIdRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBulkEmailRoute: AppBulkEmailRoute,
  AppChatRoute: AppChatRoute,
  AppCrmRoute: AppCrmRoute,
  AppDevRoute: AppDevRoute,
  AppHowToUseRoute: AppHowToUseRoute,
  AppHrRoute: AppHrRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLoginPhotosRoute: AppLoginPhotosRoute,
  AppOutreachRoute: AppOutreachRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppRecruitmentRoute: AppRecruitmentRoute,
  AppSalesRoute: AppSalesRoute,
  AppScreenMonitoringRoute: AppScreenMonitoringRoute,
  AppSeoRoute: AppSeoRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppDealsIdRoute: AppDealsIdRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
